[package]
name = "reapi-server"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = [
    "Austin Seipp <aseipp@pobox.com>"
]

[dependencies]
prost = "0.11.9"
prost-types = "0.11.9"
tokio = { version = "1.27.0", features = ["full", "tracing", "macros", "rt-multi-thread"] }
tokio-stream = "0.1.12"
tonic = "0.9.1"
tonic-reflection = "0.9.1"
tonic-health = "0.9.1"
console-subscriber = "0.1.8"

clap = { version = "4.2.2", features = ["derive"] }

[build-dependencies]
tonic-build = "0.9.1"

[profile.release]
incremental = true
lto = "fat"
strip = "debuginfo"
codegen-units = 1
opt-level = "z"
