features = ["unstable_boringssl", "bindgen"]
cfgs = [
    "boringssl",
    "osslconf=\"OPENSSL_NO_ASYNC\"",
    "osslconf=\"OPENSSL_NO_BF\"",
    "osslconf=\"OPENSSL_NO_BLAKE2\"",
    "osslconf=\"OPENSSL_NO_BUF_FREELISTS\"",
    "osslconf=\"OPENSSL_NO_CAMELLIA\"",
    "osslconf=\"OPENSSL_NO_CAPIENG\"",
    "osslconf=\"OPENSSL_NO_CAST\"",
    "osslconf=\"OPENSSL_NO_CMS\"",
    "osslconf=\"OPENSSL_NO_COMP\"",
    "osslconf=\"OPENSSL_NO_CT\"",
    "osslconf=\"OPENSSL_NO_DANE\"",
    "osslconf=\"OPENSSL_NO_DEPRECATED\"",
    "osslconf=\"OPENSSL_NO_DGRAM\"",
    "osslconf=\"OPENSSL_NO_DYNAMIC_ENGINE\"",
    "osslconf=\"OPENSSL_NO_EC_NISTP_64_GCC_128\"",
    "osslconf=\"OPENSSL_NO_EC2M\"",
    "osslconf=\"OPENSSL_NO_EGD\"",
    "osslconf=\"OPENSSL_NO_ENGINE\"",
    "osslconf=\"OPENSSL_NO_GMP\"",
    "osslconf=\"OPENSSL_NO_GOST\"",
    "osslconf=\"OPENSSL_NO_HEARTBEATS\"",
    "osslconf=\"OPENSSL_NO_HW\"",
    "osslconf=\"OPENSSL_NO_IDEA\"",
    "osslconf=\"OPENSSL_NO_JPAKE\"",
    "osslconf=\"OPENSSL_NO_KRB5\"",
    "osslconf=\"OPENSSL_NO_MD2\"",
    "osslconf=\"OPENSSL_NO_MDC2\"",
    "osslconf=\"OPENSSL_NO_OCB\"",
    "osslconf=\"OPENSSL_NO_OCSP\"",
    "osslconf=\"OPENSSL_NO_RC2\"",
    "osslconf=\"OPENSSL_NO_RC5\"",
    "osslconf=\"OPENSSL_NO_RFC3779\"",
    "osslconf=\"OPENSSL_NO_RIPEMD\"",
    "osslconf=\"OPENSSL_NO_RMD160\"",
    "osslconf=\"OPENSSL_NO_SCTP\"",
    "osslconf=\"OPENSSL_NO_SEED\"",
    "osslconf=\"OPENSSL_NO_SM2\"",
    "osslconf=\"OPENSSL_NO_SM3\"",
    "osslconf=\"OPENSSL_NO_SM4\"",
    "osslconf=\"OPENSSL_NO_SRP\"",
    "osslconf=\"OPENSSL_NO_SSL_TRACE\"",
    "osslconf=\"OPENSSL_NO_SSL2\"",
    "osslconf=\"OPENSSL_NO_SSL3\"",
    "osslconf=\"OPENSSL_NO_SSL3_METHOD\"",
    "osslconf=\"OPENSSL_NO_STATIC_ENGINE\"",
    "osslconf=\"OPENSSL_NO_STORE\"",
    "osslconf=\"OPENSSL_NO_WHIRLPOOL\"",
]

buildscript = []
